aws_config.go
=> fix: default region to ap-northeast-1

.goreleaser.yaml, Makefile
=> fix: #55 can display version

README.md
Added Spanish Translation for cls3
=> Added Spanish Translation for cls3

README.md, install.sh
This installation option would be particularly appreciated in environments where Brew is limited, such as in Linux environments. However, preferences vary, so the decision to adopt it is left to the owner.
=> feat(install): Use Script Install

README.md, action.yml, internal/app/app.go, internal/wrapper/s3_wrapper.go, internal/wrapper/s3_wrapper_test.go
This option is to hide the live display of number of deletions: 
```
Clearing... 2000 objects
```
=> feat(app): quiet mode option to hide live display of number of deletions

internal/app/app.go, internal/wrapper/s3_wrapper.go, internal/wrapper/s3_wrapper_test.go, pkg/client/s3.go, pkg/client/s3_mock.go, pkg/client/s3_test.go, testdata/deploy.sh
=> refactor: add directory buckets mode property in client object

pkg/client/s3.go
=> fix: DeleteBucket error on Directory Buckets

pkg/client/retryer.go
=> chore: use math/rand/v2

.github/actions/release/action.yml, .github/workflows/manual.yml
=> ci(deps): upgrade to goreleaser-action@v6

.github/workflows/semantic-pull-request.yml
=> ci: PR-Lint for PR titles

.github/workflows/semantic-pull-request.yml
=> ci: add main scope in PR-Lint

.github/workflows/semantic-pull-request.yml
=> ci: tweak for pr-lint

README.md
=> docs: add how to install with asdf in README

README.md
=> docs: add command option sample for -t in README

pkg/client/s3.go, pkg/client/s3_test.go
Previously, there was no ContinuationToken in the ListBuckets API, but because of the new addition.
=> feat(client): handle ContinuationToken for ListBuckets

testdata/deploy.sh, testdata/deploy_directory.sh, testdata/deploy_table.sh
=> test: improve test deploy shells

testdata/deploy_directory.sh
=> test: increase the number of buckets created in deploy_directory.sh

testdata/deploy.sh, testdata/deploy_directory.sh
=> test: wait for asynchronous loops in the test deployment shells for each constant process

testdata/deploy.sh
=> test: fix loop handling in deploy.sh

testdata/deploy_table.sh
=> test: create tables with schema in deploy_table.sh

README.md
=> docs: update gif in README

README.md
=> docs: change gif image in README

.golangci.bck.yml, .golangci.yml, pkg/client/s3_tables_test.go
=> chore: migrate golangci to v2

.gitignore
=> chore: fix .gitignore for testdata

testdata/cmd/vector/main.go
=> test: modify validation in testdata script for vector

internal/version/version_test.go
=> test(version): comment out version tests

internal/app/app.go, internal/app/app_test.go, pkg/client/aws_config.go, pkg/client/endpoint.go, pkg/client/endpoint_test.go, pkg/client/s3.go, pkg/endpoint/endpoint.go, pkg/endpoint/endpoint_test.go
=> feat: allow S3 endpoint to use -d, -t and -V options
